// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/fileserver/filserver.proto

package fileserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                          // e.g., "avatar.jpg" — you’ll generate this as UUID+ext
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // e.g., "image/jpeg"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_proto_fileserver_filserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileserver_filserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_fileserver_filserver_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // e.g., "/api/v1/image/abc123.jpg"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_proto_fileserver_filserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileserver_filserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_fileserver_filserver_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` // use filename directly (since you control it, no need for ID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_fileserver_filserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileserver_filserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_fileserver_filserver_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Stream for efficiency (avoids loading large files into memory at once)
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_fileserver_filserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileserver_filserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_fileserver_filserver_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_proto_fileserver_filserver_proto protoreflect.FileDescriptor

const file_proto_fileserver_filserver_proto_rawDesc = "" +
	"\n" +
	" proto/fileserver/filserver.proto\x12\n" +
	"fileserver\"b\n" +
	"\rUploadRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\"\n" +
	"\x0eUploadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"(\n" +
	"\n" +
	"GetRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2\x87\x01\n" +
	"\n" +
	"FileServer\x12?\n" +
	"\x06Upload\x12\x19.fileserver.UploadRequest\x1a\x1a.fileserver.UploadResponse\x128\n" +
	"\x03Get\x12\x16.fileserver.GetRequest\x1a\x17.fileserver.GetResponse0\x01B?Z=github.com/go-park-mail-ru/2025_2_Avrora/gen/proto/fileserverb\x06proto3"

var (
	file_proto_fileserver_filserver_proto_rawDescOnce sync.Once
	file_proto_fileserver_filserver_proto_rawDescData []byte
)

func file_proto_fileserver_filserver_proto_rawDescGZIP() []byte {
	file_proto_fileserver_filserver_proto_rawDescOnce.Do(func() {
		file_proto_fileserver_filserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fileserver_filserver_proto_rawDesc), len(file_proto_fileserver_filserver_proto_rawDesc)))
	})
	return file_proto_fileserver_filserver_proto_rawDescData
}

var file_proto_fileserver_filserver_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_fileserver_filserver_proto_goTypes = []any{
	(*UploadRequest)(nil),  // 0: fileserver.UploadRequest
	(*UploadResponse)(nil), // 1: fileserver.UploadResponse
	(*GetRequest)(nil),     // 2: fileserver.GetRequest
	(*GetResponse)(nil),    // 3: fileserver.GetResponse
}
var file_proto_fileserver_filserver_proto_depIdxs = []int32{
	0, // 0: fileserver.FileServer.Upload:input_type -> fileserver.UploadRequest
	2, // 1: fileserver.FileServer.Get:input_type -> fileserver.GetRequest
	1, // 2: fileserver.FileServer.Upload:output_type -> fileserver.UploadResponse
	3, // 3: fileserver.FileServer.Get:output_type -> fileserver.GetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fileserver_filserver_proto_init() }
func file_proto_fileserver_filserver_proto_init() {
	if File_proto_fileserver_filserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fileserver_filserver_proto_rawDesc), len(file_proto_fileserver_filserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fileserver_filserver_proto_goTypes,
		DependencyIndexes: file_proto_fileserver_filserver_proto_depIdxs,
		MessageInfos:      file_proto_fileserver_filserver_proto_msgTypes,
	}.Build()
	File_proto_fileserver_filserver_proto = out.File
	file_proto_fileserver_filserver_proto_goTypes = nil
	file_proto_fileserver_filserver_proto_depIdxs = nil
}
