version: "2"

run:
  timeout: 5m
  go: '1.25'

linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - nilerr
    - nilnesserr
    - wrapcheck
    - contextcheck
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - bodyclose
    - gosec
    - staticcheck
    - unused
    - ineffassign
    - unconvert
    - makezero
    - musttag
    - revive
    - depguard
    - importas
    - paralleltest
    - testifylint
    - misspell
    - whitespace
    - copyloopvar

formatters:
  enable:
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gosec:
    excludes:
      - G404

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/golang-jwt/jwt/v5
          - github.com/golang-migrate/migrate/v4
          - github.com/go-park-mail-ru/2025_2_Avrora/internal/...
          - go.uber.org/zap
          - github.com/jackc/pgx/v5
          - github.com/jackc/pgx/v5/stdlib
          - github.com/google/uuid
          - golang.org/x/crypto/bcrypt

  revive:
    rules:
      - name: var-naming

  wrapcheck:
    ignore-interface-regexps:
      - '^(?i)c(?-i)ach(ing|e)'

issues:
  max-same-issues: 0
  max-per-linter: 0
  uniq-by-line: true

output:
  formats:
    text:
      path: stdout
      colors: true