// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers(in *jlexer.Lexer, out *WebhookRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "event":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Event = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "object":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Object).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers(out *jwriter.Writer, in WebhookRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix[1:])
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"object\":"
		out.RawString(prefix)
		(in.Object).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WebhookRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WebhookRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WebhookRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WebhookRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers1(in *jlexer.Lexer, out *UpdateOfferRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "in_housing_complex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InHousingComplex = bool(in.Bool())
			}
		case "housing_complex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HousingComplex = string(in.String())
			}
		case "offer_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OfferType = string(in.String())
			}
		case "property_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PropertyType = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "floor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Floor = int(in.Int())
			}
		case "total_floors":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalFloors = int(in.Int())
			}
		case "rooms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rooms = int(in.Int())
			}
		case "area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "living_area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LivingArea = float64(in.Float64())
			}
		case "kitchen_area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KitchenArea = float64(in.Float64())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "deposit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Deposit = int64(in.Int64())
			}
		case "commission":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Commission = int64(in.Int64())
			}
		case "rental_period":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RentalPeriod = string(in.String())
			}
		case "image_urls":
			if in.IsNull() {
				in.Skip()
				out.ImageURLs = nil
			} else {
				in.Delim('[')
				if out.ImageURLs == nil {
					if !in.IsDelim(']') {
						out.ImageURLs = make([]string, 0, 4)
					} else {
						out.ImageURLs = []string{}
					}
				} else {
					out.ImageURLs = (out.ImageURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.ImageURLs = append(out.ImageURLs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers1(out *jwriter.Writer, in UpdateOfferRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"in_housing_complex\":"
		out.RawString(prefix)
		out.Bool(bool(in.InHousingComplex))
	}
	{
		const prefix string = ",\"housing_complex\":"
		out.RawString(prefix)
		out.String(string(in.HousingComplex))
	}
	{
		const prefix string = ",\"offer_type\":"
		out.RawString(prefix)
		out.String(string(in.OfferType))
	}
	{
		const prefix string = ",\"property_type\":"
		out.RawString(prefix)
		out.String(string(in.PropertyType))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"total_floors\":"
		out.RawString(prefix)
		out.Int(int(in.TotalFloors))
	}
	{
		const prefix string = ",\"rooms\":"
		out.RawString(prefix)
		out.Int(int(in.Rooms))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"living_area\":"
		out.RawString(prefix)
		out.Float64(float64(in.LivingArea))
	}
	{
		const prefix string = ",\"kitchen_area\":"
		out.RawString(prefix)
		out.Float64(float64(in.KitchenArea))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"deposit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Deposit))
	}
	{
		const prefix string = ",\"commission\":"
		out.RawString(prefix)
		out.Int64(int64(in.Commission))
	}
	{
		const prefix string = ",\"rental_period\":"
		out.RawString(prefix)
		out.String(string(in.RentalPeriod))
	}
	{
		const prefix string = ",\"image_urls\":"
		out.RawString(prefix)
		if in.ImageURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.ImageURLs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateOfferRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateOfferRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateOfferRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateOfferRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers1(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers2(in *jlexer.Lexer, out *ThreeDSecureDetails) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "applied":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Applied = bool(in.Bool())
			}
		case "challenge_completed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChallengeCompleted = bool(in.Bool())
			}
		case "method_completed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MethodCompleted = bool(in.Bool())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers2(out *jwriter.Writer, in ThreeDSecureDetails) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"applied\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Applied))
	}
	{
		const prefix string = ",\"challenge_completed\":"
		out.RawString(prefix)
		out.Bool(bool(in.ChallengeCompleted))
	}
	{
		const prefix string = ",\"method_completed\":"
		out.RawString(prefix)
		out.Bool(bool(in.MethodCompleted))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ThreeDSecureDetails) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ThreeDSecureDetails) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ThreeDSecureDetails) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ThreeDSecureDetails) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers2(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers3(in *jlexer.Lexer, out *Recipient) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "gateway_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GatewayID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers3(out *jwriter.Writer, in Recipient) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"gateway_id\":"
		out.RawString(prefix)
		out.String(string(in.GatewayID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Recipient) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Recipient) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Recipient) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Recipient) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers3(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers4(in *jlexer.Lexer, out *PaymentMethod) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "card":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Card).UnmarshalEasyJSON(in)
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "saved":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Saved = bool(in.Bool())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers4(out *jwriter.Writer, in PaymentMethod) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"card\":"
		out.RawString(prefix[1:])
		(in.Card).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"saved\":"
		out.RawString(prefix)
		out.Bool(bool(in.Saved))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentMethod) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentMethod) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentMethod) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentMethod) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers4(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers5(in *jlexer.Lexer, out *Payment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Amount).UnmarshalEasyJSON(in)
			}
		case "authorization_details":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.AuthorizationDetails).UnmarshalEasyJSON(in)
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "expires_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiresAt = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Metadata = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					(out.Metadata)[key] = v4
					in.WantComma()
				}
				in.Delim('}')
			}
		case "paid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Paid = bool(in.Bool())
			}
		case "payment_method":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.PaymentMethod).UnmarshalEasyJSON(in)
			}
		case "recipient":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Recipient).UnmarshalEasyJSON(in)
			}
		case "refundable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Refundable = bool(in.Bool())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "test":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Test = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers5(out *jwriter.Writer, in Payment) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		(in.Amount).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"authorization_details\":"
		out.RawString(prefix)
		(in.AuthorizationDetails).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"expires_at\":"
		out.RawString(prefix)
		out.String(string(in.ExpiresAt))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		if in.Metadata == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.Metadata {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				out.String(string(v5Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"paid\":"
		out.RawString(prefix)
		out.Bool(bool(in.Paid))
	}
	{
		const prefix string = ",\"payment_method\":"
		out.RawString(prefix)
		(in.PaymentMethod).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		(in.Recipient).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"refundable\":"
		out.RawString(prefix)
		out.Bool(bool(in.Refundable))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"test\":"
		out.RawString(prefix)
		out.Bool(bool(in.Test))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Payment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Payment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Payment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Payment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers5(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers6(in *jlexer.Lexer, out *OfferInFeedResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int(in.Int())
			}
		case "offer_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OfferURL = string(in.String())
			}
		case "offer_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OfferType = string(in.String())
			}
		case "property_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PropertyType = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "rooms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rooms = int(in.Int())
			}
		case "floor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Floor = int(in.Int())
			}
		case "total_floors":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalFloors = int(in.Int())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "metro":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Metro = string(in.String())
			}
		case "image_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImageURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers6(out *jwriter.Writer, in OfferInFeedResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int(int(in.UserID))
	}
	{
		const prefix string = ",\"offer_url\":"
		out.RawString(prefix)
		out.String(string(in.OfferURL))
	}
	{
		const prefix string = ",\"offer_type\":"
		out.RawString(prefix)
		out.String(string(in.OfferType))
	}
	{
		const prefix string = ",\"property_type\":"
		out.RawString(prefix)
		out.String(string(in.PropertyType))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"rooms\":"
		out.RawString(prefix)
		out.Int(int(in.Rooms))
	}
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"total_floors\":"
		out.RawString(prefix)
		out.Int(int(in.TotalFloors))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"metro\":"
		out.RawString(prefix)
		out.String(string(in.Metro))
	}
	{
		const prefix string = ",\"image_url\":"
		out.RawString(prefix)
		out.String(string(in.ImageURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OfferInFeedResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OfferInFeedResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OfferInFeedResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OfferInFeedResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers6(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers7(in *jlexer.Lexer, out *FullOfferResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "in_housing_complex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InHousingComplex = bool(in.Bool())
			}
		case "housing_complex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HousingComplex = string(in.String())
			}
		case "offer_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OfferType = string(in.String())
			}
		case "property_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PropertyType = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "floor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Floor = int(in.Int())
			}
		case "total_floors":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalFloors = int(in.Int())
			}
		case "rooms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rooms = int(in.Int())
			}
		case "area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "living_area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LivingArea = float64(in.Float64())
			}
		case "kitchen_area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KitchenArea = float64(in.Float64())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "deposit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Deposit = float64(in.Float64())
			}
		case "commission":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Commission = float64(in.Float64())
			}
		case "rental_period":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RentalPeriod = string(in.String())
			}
		case "metro":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Metro = string(in.String())
			}
		case "image_urls":
			if in.IsNull() {
				in.Skip()
				out.ImageURLs = nil
			} else {
				in.Delim('[')
				if out.ImageURLs == nil {
					if !in.IsDelim(']') {
						out.ImageURLs = make([]string, 0, 4)
					} else {
						out.ImageURLs = []string{}
					}
				} else {
					out.ImageURLs = (out.ImageURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v6 string
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = string(in.String())
					}
					out.ImageURLs = append(out.ImageURLs, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers7(out *jwriter.Writer, in FullOfferResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"in_housing_complex\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.InHousingComplex))
	}
	{
		const prefix string = ",\"housing_complex\":"
		out.RawString(prefix)
		out.String(string(in.HousingComplex))
	}
	{
		const prefix string = ",\"offer_type\":"
		out.RawString(prefix)
		out.String(string(in.OfferType))
	}
	{
		const prefix string = ",\"property_type\":"
		out.RawString(prefix)
		out.String(string(in.PropertyType))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"total_floors\":"
		out.RawString(prefix)
		out.Int(int(in.TotalFloors))
	}
	{
		const prefix string = ",\"rooms\":"
		out.RawString(prefix)
		out.Int(int(in.Rooms))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"living_area\":"
		out.RawString(prefix)
		out.Float64(float64(in.LivingArea))
	}
	{
		const prefix string = ",\"kitchen_area\":"
		out.RawString(prefix)
		out.Float64(float64(in.KitchenArea))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"deposit\":"
		out.RawString(prefix)
		out.Float64(float64(in.Deposit))
	}
	{
		const prefix string = ",\"commission\":"
		out.RawString(prefix)
		out.Float64(float64(in.Commission))
	}
	{
		const prefix string = ",\"rental_period\":"
		out.RawString(prefix)
		out.String(string(in.RentalPeriod))
	}
	{
		const prefix string = ",\"metro\":"
		out.RawString(prefix)
		out.String(string(in.Metro))
	}
	{
		const prefix string = ",\"image_urls\":"
		out.RawString(prefix)
		if in.ImageURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.ImageURLs {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FullOfferResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FullOfferResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FullOfferResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FullOfferResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers7(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers8(in *jlexer.Lexer, out *CreateOfferRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "in_housing_complex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InHousingComplex = bool(in.Bool())
			}
		case "housing_complex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HousingComplex = string(in.String())
			}
		case "offer_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OfferType = string(in.String())
			}
		case "property_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PropertyType = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "floor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Floor = int(in.Int())
			}
		case "total_floors":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalFloors = int(in.Int())
			}
		case "rooms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rooms = int(in.Int())
			}
		case "area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "living_area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LivingArea = float64(in.Float64())
			}
		case "kitchen_area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KitchenArea = float64(in.Float64())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "deposit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Deposit = int64(in.Int64())
			}
		case "commission":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Commission = int64(in.Int64())
			}
		case "rental_period":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RentalPeriod = string(in.String())
			}
		case "image_urls":
			if in.IsNull() {
				in.Skip()
				out.ImageURLs = nil
			} else {
				in.Delim('[')
				if out.ImageURLs == nil {
					if !in.IsDelim(']') {
						out.ImageURLs = make([]string, 0, 4)
					} else {
						out.ImageURLs = []string{}
					}
				} else {
					out.ImageURLs = (out.ImageURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v9 string
					if in.IsNull() {
						in.Skip()
					} else {
						v9 = string(in.String())
					}
					out.ImageURLs = append(out.ImageURLs, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers8(out *jwriter.Writer, in CreateOfferRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"in_housing_complex\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.InHousingComplex))
	}
	{
		const prefix string = ",\"housing_complex\":"
		out.RawString(prefix)
		out.String(string(in.HousingComplex))
	}
	{
		const prefix string = ",\"offer_type\":"
		out.RawString(prefix)
		out.String(string(in.OfferType))
	}
	{
		const prefix string = ",\"property_type\":"
		out.RawString(prefix)
		out.String(string(in.PropertyType))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"total_floors\":"
		out.RawString(prefix)
		out.Int(int(in.TotalFloors))
	}
	{
		const prefix string = ",\"rooms\":"
		out.RawString(prefix)
		out.Int(int(in.Rooms))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"living_area\":"
		out.RawString(prefix)
		out.Float64(float64(in.LivingArea))
	}
	{
		const prefix string = ",\"kitchen_area\":"
		out.RawString(prefix)
		out.Float64(float64(in.KitchenArea))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"deposit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Deposit))
	}
	{
		const prefix string = ",\"commission\":"
		out.RawString(prefix)
		out.Int64(int64(in.Commission))
	}
	{
		const prefix string = ",\"rental_period\":"
		out.RawString(prefix)
		out.String(string(in.RentalPeriod))
	}
	{
		const prefix string = ",\"image_urls\":"
		out.RawString(prefix)
		if in.ImageURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.ImageURLs {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateOfferRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateOfferRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateOfferRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateOfferRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers8(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers9(in *jlexer.Lexer, out *CardProductDetails) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers9(out *jwriter.Writer, in CardProductDetails) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CardProductDetails) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CardProductDetails) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CardProductDetails) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CardProductDetails) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers9(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers10(in *jlexer.Lexer, out *CardDetails) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "card_product":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.CardProduct).UnmarshalEasyJSON(in)
			}
		case "card_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CardType = string(in.String())
			}
		case "expiry_month":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiryMonth = string(in.String())
			}
		case "expiry_year":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiryYear = string(in.String())
			}
		case "first6":
			if in.IsNull() {
				in.Skip()
			} else {
				out.First6 = string(in.String())
			}
		case "issuer_country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IssuerCountry = string(in.String())
			}
		case "last4":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Last4 = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers10(out *jwriter.Writer, in CardDetails) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"card_product\":"
		out.RawString(prefix[1:])
		(in.CardProduct).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"card_type\":"
		out.RawString(prefix)
		out.String(string(in.CardType))
	}
	{
		const prefix string = ",\"expiry_month\":"
		out.RawString(prefix)
		out.String(string(in.ExpiryMonth))
	}
	{
		const prefix string = ",\"expiry_year\":"
		out.RawString(prefix)
		out.String(string(in.ExpiryYear))
	}
	{
		const prefix string = ",\"first6\":"
		out.RawString(prefix)
		out.String(string(in.First6))
	}
	{
		const prefix string = ",\"issuer_country\":"
		out.RawString(prefix)
		out.String(string(in.IssuerCountry))
	}
	{
		const prefix string = ",\"last4\":"
		out.RawString(prefix)
		out.String(string(in.Last4))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CardDetails) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CardDetails) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CardDetails) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CardDetails) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers10(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers11(in *jlexer.Lexer, out *AuthorizationDetails) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "auth_code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AuthCode = string(in.String())
			}
		case "rrn":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RRN = string(in.String())
			}
		case "three_d_secure":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.ThreeDSecure).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers11(out *jwriter.Writer, in AuthorizationDetails) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"auth_code\":"
		out.RawString(prefix[1:])
		out.String(string(in.AuthCode))
	}
	{
		const prefix string = ",\"rrn\":"
		out.RawString(prefix)
		out.String(string(in.RRN))
	}
	{
		const prefix string = ",\"three_d_secure\":"
		out.RawString(prefix)
		(in.ThreeDSecure).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AuthorizationDetails) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AuthorizationDetails) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AuthorizationDetails) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AuthorizationDetails) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers11(l, v)
}
func easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers12(in *jlexer.Lexer, out *AmountDetails) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers12(out *jwriter.Writer, in AmountDetails) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"currency\":"
		out.RawString(prefix[1:])
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AmountDetails) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AmountDetails) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16af6ffEncodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AmountDetails) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AmountDetails) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16af6ffDecodeGithubComGoParkMailRu20252AvroraInternalDeliveryHttpHandlers12(l, v)
}
