// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain(in *jlexer.Lexer, out *HousingComplex) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "YearBuilt":
			if in.IsNull() {
				in.Skip()
				out.YearBuilt = nil
			} else {
				if out.YearBuilt == nil {
					out.YearBuilt = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.YearBuilt = int(in.Int())
				}
			}
		case "LocationID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LocationID = string(in.String())
			}
		case "Developer":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Developer = string(in.String())
			}
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "StartingPrice":
			if in.IsNull() {
				in.Skip()
				out.StartingPrice = nil
			} else {
				if out.StartingPrice == nil {
					out.StartingPrice = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.StartingPrice = int64(in.Int64())
				}
			}
		case "ImageURLs":
			if in.IsNull() {
				in.Skip()
				out.ImageURLs = nil
			} else {
				in.Delim('[')
				if out.ImageURLs == nil {
					if !in.IsDelim(']') {
						out.ImageURLs = make([]string, 0, 4)
					} else {
						out.ImageURLs = []string{}
					}
				} else {
					out.ImageURLs = (out.ImageURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.ImageURLs = append(out.ImageURLs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain(out *jwriter.Writer, in HousingComplex) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"YearBuilt\":"
		out.RawString(prefix)
		if in.YearBuilt == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.YearBuilt))
		}
	}
	{
		const prefix string = ",\"LocationID\":"
		out.RawString(prefix)
		out.String(string(in.LocationID))
	}
	{
		const prefix string = ",\"Developer\":"
		out.RawString(prefix)
		out.String(string(in.Developer))
	}
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"StartingPrice\":"
		out.RawString(prefix)
		if in.StartingPrice == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.StartingPrice))
		}
	}
	{
		const prefix string = ",\"ImageURLs\":"
		out.RawString(prefix)
		if in.ImageURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.ImageURLs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HousingComplex) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HousingComplex) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HousingComplex) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HousingComplex) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain(l, v)
}
func easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain1(in *jlexer.Lexer, out *ComplexesInFeed) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Meta":
			easyjson86c2dad6Decode(in, &out.Meta)
		case "Complexes":
			if in.IsNull() {
				in.Skip()
				out.Complexes = nil
			} else {
				in.Delim('[')
				if out.Complexes == nil {
					if !in.IsDelim(']') {
						out.Complexes = make([]ComplexInFeed, 0, 0)
					} else {
						out.Complexes = []ComplexInFeed{}
					}
				} else {
					out.Complexes = (out.Complexes)[:0]
				}
				for !in.IsDelim(']') {
					var v4 ComplexInFeed
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Complexes = append(out.Complexes, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain1(out *jwriter.Writer, in ComplexesInFeed) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Meta\":"
		out.RawString(prefix[1:])
		easyjson86c2dad6Encode(out, in.Meta)
	}
	{
		const prefix string = ",\"Complexes\":"
		out.RawString(prefix)
		if in.Complexes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Complexes {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ComplexesInFeed) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ComplexesInFeed) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ComplexesInFeed) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ComplexesInFeed) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain1(l, v)
}
func easyjson86c2dad6Decode(in *jlexer.Lexer, out *struct {
	Total  int
	Offset int
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "Offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6Encode(out *jwriter.Writer, in struct {
	Total  int
	Offset int
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Total\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"Offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}
func easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain2(in *jlexer.Lexer, out *ComplexInFeed) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "StartingPrice":
			if in.IsNull() {
				in.Skip()
				out.StartingPrice = nil
			} else {
				if out.StartingPrice == nil {
					out.StartingPrice = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.StartingPrice = int64(in.Int64())
				}
			}
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "Metro":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Metro = string(in.String())
			}
		case "ImageURL":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImageURL = string(in.String())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain2(out *jwriter.Writer, in ComplexInFeed) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"StartingPrice\":"
		out.RawString(prefix)
		if in.StartingPrice == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.StartingPrice))
		}
	}
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"Metro\":"
		out.RawString(prefix)
		out.String(string(in.Metro))
	}
	{
		const prefix string = ",\"ImageURL\":"
		out.RawString(prefix)
		out.String(string(in.ImageURL))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ComplexInFeed) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ComplexInFeed) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86c2dad6EncodeGithubComGoParkMailRu20252AvroraInternalDomain2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ComplexInFeed) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ComplexInFeed) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86c2dad6DecodeGithubComGoParkMailRu20252AvroraInternalDomain2(l, v)
}
