// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain(in *jlexer.Lexer, out *PricePoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Date).UnmarshalJSON(data))
				}
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain(out *jwriter.Writer, in PricePoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.Raw((in.Date).MarshalJSON())
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PricePoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PricePoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PricePoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PricePoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain(l, v)
}
func easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain1(in *jlexer.Lexer, out *OffersInFeed) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Meta":
			easyjsonB1f7ff84Decode(in, &out.Meta)
		case "Offers":
			if in.IsNull() {
				in.Skip()
				out.Offers = nil
			} else {
				in.Delim('[')
				if out.Offers == nil {
					if !in.IsDelim(']') {
						out.Offers = make([]OfferInFeed, 0, 0)
					} else {
						out.Offers = []OfferInFeed{}
					}
				} else {
					out.Offers = (out.Offers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 OfferInFeed
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Offers = append(out.Offers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain1(out *jwriter.Writer, in OffersInFeed) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Meta\":"
		out.RawString(prefix[1:])
		easyjsonB1f7ff84Encode(out, in.Meta)
	}
	{
		const prefix string = ",\"Offers\":"
		out.RawString(prefix)
		if in.Offers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Offers {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OffersInFeed) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OffersInFeed) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OffersInFeed) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OffersInFeed) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain1(l, v)
}
func easyjsonB1f7ff84Decode(in *jlexer.Lexer, out *struct {
	Total  int
	Offset int
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "Offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1f7ff84Encode(out *jwriter.Writer, in struct {
	Total  int
	Offset int
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Total\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"Offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}
func easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain2(in *jlexer.Lexer, out *OfferInFeed) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "OfferType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OfferType = OfferType(in.String())
			}
		case "PropertyType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PropertyType = PropertyType(in.String())
			}
		case "Price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		case "Area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "Rooms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rooms = int(in.Int())
			}
		case "Floor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Floor = int(in.Int())
			}
		case "TotalFloors":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalFloors = int(in.Int())
			}
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "Metro":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Metro = string(in.String())
			}
		case "ImageURL":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImageURL = string(in.String())
			}
		case "ViewCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ViewCount = int(in.Int())
			}
		case "LikeCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LikeCount = int(in.Int())
			}
		case "IsLiked":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsLiked = bool(in.Bool())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain2(out *jwriter.Writer, in OfferInFeed) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"OfferType\":"
		out.RawString(prefix)
		out.String(string(in.OfferType))
	}
	{
		const prefix string = ",\"PropertyType\":"
		out.RawString(prefix)
		out.String(string(in.PropertyType))
	}
	{
		const prefix string = ",\"Price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	{
		const prefix string = ",\"Area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"Rooms\":"
		out.RawString(prefix)
		out.Int(int(in.Rooms))
	}
	{
		const prefix string = ",\"Floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"TotalFloors\":"
		out.RawString(prefix)
		out.Int(int(in.TotalFloors))
	}
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"Metro\":"
		out.RawString(prefix)
		out.String(string(in.Metro))
	}
	{
		const prefix string = ",\"ImageURL\":"
		out.RawString(prefix)
		out.String(string(in.ImageURL))
	}
	{
		const prefix string = ",\"ViewCount\":"
		out.RawString(prefix)
		out.Int(int(in.ViewCount))
	}
	{
		const prefix string = ",\"LikeCount\":"
		out.RawString(prefix)
		out.Int(int(in.LikeCount))
	}
	{
		const prefix string = ",\"IsLiked\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsLiked))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OfferInFeed) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OfferInFeed) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OfferInFeed) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OfferInFeed) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain2(l, v)
}
func easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain3(in *jlexer.Lexer, out *OfferFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "offer_type":
			if in.IsNull() {
				in.Skip()
				out.OfferType = nil
			} else {
				if out.OfferType == nil {
					out.OfferType = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.OfferType = string(in.String())
				}
			}
		case "property_type":
			if in.IsNull() {
				in.Skip()
				out.PropertyType = nil
			} else {
				if out.PropertyType == nil {
					out.PropertyType = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PropertyType = string(in.String())
				}
			}
		case "rooms":
			if in.IsNull() {
				in.Skip()
				out.Rooms = nil
			} else {
				if out.Rooms == nil {
					out.Rooms = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Rooms = int(in.Int())
				}
			}
		case "price_min":
			if in.IsNull() {
				in.Skip()
				out.PriceMin = nil
			} else {
				if out.PriceMin == nil {
					out.PriceMin = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PriceMin = int64(in.Int64())
				}
			}
		case "price_max":
			if in.IsNull() {
				in.Skip()
				out.PriceMax = nil
			} else {
				if out.PriceMax == nil {
					out.PriceMax = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PriceMax = int64(in.Int64())
				}
			}
		case "area_min":
			if in.IsNull() {
				in.Skip()
				out.AreaMin = nil
			} else {
				if out.AreaMin == nil {
					out.AreaMin = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AreaMin = float64(in.Float64())
				}
			}
		case "area_max":
			if in.IsNull() {
				in.Skip()
				out.AreaMax = nil
			} else {
				if out.AreaMax == nil {
					out.AreaMax = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AreaMax = float64(in.Float64())
				}
			}
		case "status":
			if in.IsNull() {
				in.Skip()
				out.Status = nil
			} else {
				if out.Status == nil {
					out.Status = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Status = string(in.String())
				}
			}
		case "utug":
			if in.IsNull() {
				in.Skip()
				out.Utug = nil
			} else {
				if out.Utug == nil {
					out.Utug = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Utug = bool(in.Bool())
				}
			}
		case "address":
			if in.IsNull() {
				in.Skip()
				out.Address = nil
			} else {
				if out.Address == nil {
					out.Address = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Address = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain3(out *jwriter.Writer, in OfferFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"offer_type\":"
		out.RawString(prefix[1:])
		if in.OfferType == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.OfferType))
		}
	}
	{
		const prefix string = ",\"property_type\":"
		out.RawString(prefix)
		if in.PropertyType == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PropertyType))
		}
	}
	{
		const prefix string = ",\"rooms\":"
		out.RawString(prefix)
		if in.Rooms == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.Rooms))
		}
	}
	{
		const prefix string = ",\"price_min\":"
		out.RawString(prefix)
		if in.PriceMin == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.PriceMin))
		}
	}
	{
		const prefix string = ",\"price_max\":"
		out.RawString(prefix)
		if in.PriceMax == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.PriceMax))
		}
	}
	{
		const prefix string = ",\"area_min\":"
		out.RawString(prefix)
		if in.AreaMin == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.AreaMin))
		}
	}
	{
		const prefix string = ",\"area_max\":"
		out.RawString(prefix)
		if in.AreaMax == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.AreaMax))
		}
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		if in.Status == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Status))
		}
	}
	{
		const prefix string = ",\"utug\":"
		out.RawString(prefix)
		if in.Utug == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.Utug))
		}
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		if in.Address == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Address))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OfferFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OfferFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OfferFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OfferFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain3(l, v)
}
func easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain4(in *jlexer.Lexer, out *OfferCreate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "HousingComplexID":
			if in.IsNull() {
				in.Skip()
				out.HousingComplexID = nil
			} else {
				if out.HousingComplexID == nil {
					out.HousingComplexID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.HousingComplexID = string(in.String())
				}
			}
		case "OfferType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OfferType = OfferType(in.String())
			}
		case "PropertyType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PropertyType = PropertyType(in.String())
			}
		case "Title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "Price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		case "Area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "Rooms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rooms = int(in.Int())
			}
		case "Floor":
			if in.IsNull() {
				in.Skip()
				out.Floor = nil
			} else {
				if out.Floor == nil {
					out.Floor = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Floor = int(in.Int())
				}
			}
		case "TotalFloors":
			if in.IsNull() {
				in.Skip()
				out.TotalFloors = nil
			} else {
				if out.TotalFloors == nil {
					out.TotalFloors = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.TotalFloors = int(in.Int())
				}
			}
		case "Deposit":
			if in.IsNull() {
				in.Skip()
				out.Deposit = nil
			} else {
				if out.Deposit == nil {
					out.Deposit = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Deposit = int64(in.Int64())
				}
			}
		case "Commission":
			if in.IsNull() {
				in.Skip()
				out.Commission = nil
			} else {
				if out.Commission == nil {
					out.Commission = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Commission = int64(in.Int64())
				}
			}
		case "RentalPeriod":
			if in.IsNull() {
				in.Skip()
				out.RentalPeriod = nil
			} else {
				if out.RentalPeriod == nil {
					out.RentalPeriod = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.RentalPeriod = string(in.String())
				}
			}
		case "LivingArea":
			if in.IsNull() {
				in.Skip()
				out.LivingArea = nil
			} else {
				if out.LivingArea == nil {
					out.LivingArea = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LivingArea = float64(in.Float64())
				}
			}
		case "KitchenArea":
			if in.IsNull() {
				in.Skip()
				out.KitchenArea = nil
			} else {
				if out.KitchenArea == nil {
					out.KitchenArea = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.KitchenArea = float64(in.Float64())
				}
			}
		case "ImageURLs":
			if in.IsNull() {
				in.Skip()
				out.ImageURLs = nil
			} else {
				in.Delim('[')
				if out.ImageURLs == nil {
					if !in.IsDelim(']') {
						out.ImageURLs = make([]string, 0, 4)
					} else {
						out.ImageURLs = []string{}
					}
				} else {
					out.ImageURLs = (out.ImageURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.ImageURLs = append(out.ImageURLs, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain4(out *jwriter.Writer, in OfferCreate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"HousingComplexID\":"
		out.RawString(prefix[1:])
		if in.HousingComplexID == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.HousingComplexID))
		}
	}
	{
		const prefix string = ",\"OfferType\":"
		out.RawString(prefix)
		out.String(string(in.OfferType))
	}
	{
		const prefix string = ",\"PropertyType\":"
		out.RawString(prefix)
		out.String(string(in.PropertyType))
	}
	{
		const prefix string = ",\"Title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"Price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	{
		const prefix string = ",\"Area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"Rooms\":"
		out.RawString(prefix)
		out.Int(int(in.Rooms))
	}
	{
		const prefix string = ",\"Floor\":"
		out.RawString(prefix)
		if in.Floor == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.Floor))
		}
	}
	{
		const prefix string = ",\"TotalFloors\":"
		out.RawString(prefix)
		if in.TotalFloors == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.TotalFloors))
		}
	}
	{
		const prefix string = ",\"Deposit\":"
		out.RawString(prefix)
		if in.Deposit == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Deposit))
		}
	}
	{
		const prefix string = ",\"Commission\":"
		out.RawString(prefix)
		if in.Commission == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Commission))
		}
	}
	{
		const prefix string = ",\"RentalPeriod\":"
		out.RawString(prefix)
		if in.RentalPeriod == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.RentalPeriod))
		}
	}
	{
		const prefix string = ",\"LivingArea\":"
		out.RawString(prefix)
		if in.LivingArea == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.LivingArea))
		}
	}
	{
		const prefix string = ",\"KitchenArea\":"
		out.RawString(prefix)
		if in.KitchenArea == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.KitchenArea))
		}
	}
	{
		const prefix string = ",\"ImageURLs\":"
		out.RawString(prefix)
		if in.ImageURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.ImageURLs {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OfferCreate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OfferCreate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OfferCreate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OfferCreate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain4(l, v)
}
func easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain5(in *jlexer.Lexer, out *Offer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "LocationID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LocationID = string(in.String())
			}
		case "HousingComplexID":
			if in.IsNull() {
				in.Skip()
				out.HousingComplexID = nil
			} else {
				if out.HousingComplexID == nil {
					out.HousingComplexID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.HousingComplexID = string(in.String())
				}
			}
		case "Title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "Price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		case "Area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "Rooms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rooms = int(in.Int())
			}
		case "PropertyType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PropertyType = PropertyType(in.String())
			}
		case "OfferType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OfferType = OfferType(in.String())
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = OfferStatus(in.String())
			}
		case "Floor":
			if in.IsNull() {
				in.Skip()
				out.Floor = nil
			} else {
				if out.Floor == nil {
					out.Floor = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Floor = int(in.Int())
				}
			}
		case "TotalFloors":
			if in.IsNull() {
				in.Skip()
				out.TotalFloors = nil
			} else {
				if out.TotalFloors == nil {
					out.TotalFloors = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.TotalFloors = int(in.Int())
				}
			}
		case "Deposit":
			if in.IsNull() {
				in.Skip()
				out.Deposit = nil
			} else {
				if out.Deposit == nil {
					out.Deposit = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Deposit = int64(in.Int64())
				}
			}
		case "Commission":
			if in.IsNull() {
				in.Skip()
				out.Commission = nil
			} else {
				if out.Commission == nil {
					out.Commission = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Commission = int64(in.Int64())
				}
			}
		case "RentalPeriod":
			if in.IsNull() {
				in.Skip()
				out.RentalPeriod = nil
			} else {
				if out.RentalPeriod == nil {
					out.RentalPeriod = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.RentalPeriod = string(in.String())
				}
			}
		case "LivingArea":
			if in.IsNull() {
				in.Skip()
				out.LivingArea = nil
			} else {
				if out.LivingArea == nil {
					out.LivingArea = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LivingArea = float64(in.Float64())
				}
			}
		case "KitchenArea":
			if in.IsNull() {
				in.Skip()
				out.KitchenArea = nil
			} else {
				if out.KitchenArea == nil {
					out.KitchenArea = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.KitchenArea = float64(in.Float64())
				}
			}
		case "Metro":
			if in.IsNull() {
				in.Skip()
				out.Metro = nil
			} else {
				if out.Metro == nil {
					out.Metro = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Metro = string(in.String())
				}
			}
		case "ImageURLs":
			if in.IsNull() {
				in.Skip()
				out.ImageURLs = nil
			} else {
				in.Delim('[')
				if out.ImageURLs == nil {
					if !in.IsDelim(']') {
						out.ImageURLs = make([]string, 0, 4)
					} else {
						out.ImageURLs = []string{}
					}
				} else {
					out.ImageURLs = (out.ImageURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					out.ImageURLs = append(out.ImageURLs, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain5(out *jwriter.Writer, in Offer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"LocationID\":"
		out.RawString(prefix)
		out.String(string(in.LocationID))
	}
	{
		const prefix string = ",\"HousingComplexID\":"
		out.RawString(prefix)
		if in.HousingComplexID == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.HousingComplexID))
		}
	}
	{
		const prefix string = ",\"Title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"Price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	{
		const prefix string = ",\"Area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"Rooms\":"
		out.RawString(prefix)
		out.Int(int(in.Rooms))
	}
	{
		const prefix string = ",\"PropertyType\":"
		out.RawString(prefix)
		out.String(string(in.PropertyType))
	}
	{
		const prefix string = ",\"OfferType\":"
		out.RawString(prefix)
		out.String(string(in.OfferType))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"Floor\":"
		out.RawString(prefix)
		if in.Floor == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.Floor))
		}
	}
	{
		const prefix string = ",\"TotalFloors\":"
		out.RawString(prefix)
		if in.TotalFloors == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.TotalFloors))
		}
	}
	{
		const prefix string = ",\"Deposit\":"
		out.RawString(prefix)
		if in.Deposit == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Deposit))
		}
	}
	{
		const prefix string = ",\"Commission\":"
		out.RawString(prefix)
		if in.Commission == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Commission))
		}
	}
	{
		const prefix string = ",\"RentalPeriod\":"
		out.RawString(prefix)
		if in.RentalPeriod == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.RentalPeriod))
		}
	}
	{
		const prefix string = ",\"LivingArea\":"
		out.RawString(prefix)
		if in.LivingArea == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.LivingArea))
		}
	}
	{
		const prefix string = ",\"KitchenArea\":"
		out.RawString(prefix)
		if in.KitchenArea == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.KitchenArea))
		}
	}
	{
		const prefix string = ",\"Metro\":"
		out.RawString(prefix)
		if in.Metro == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Metro))
		}
	}
	{
		const prefix string = ",\"ImageURLs\":"
		out.RawString(prefix)
		if in.ImageURLs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.ImageURLs {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Offer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Offer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Offer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Offer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain5(l, v)
}
func easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain6(in *jlexer.Lexer, out *FirstPhotosForOffers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Photos":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Photos = make(map[OfferID]PhotoURL)
				for !in.IsDelim('}') {
					key := OfferID(in.String())
					in.WantColon()
					var v10 PhotoURL
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = PhotoURL(in.String())
					}
					(out.Photos)[key] = v10
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain6(out *jwriter.Writer, in FirstPhotosForOffers) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Photos\":"
		out.RawString(prefix[1:])
		if in.Photos == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v11First := true
			for v11Name, v11Value := range in.Photos {
				if v11First {
					v11First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v11Name))
				out.RawByte(':')
				out.String(string(v11Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FirstPhotosForOffers) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FirstPhotosForOffers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1f7ff84EncodeGithubComGoParkMailRu20252AvroraInternalDomain6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FirstPhotosForOffers) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FirstPhotosForOffers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1f7ff84DecodeGithubComGoParkMailRu20252AvroraInternalDomain6(l, v)
}
