// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  domain

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Err ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Err ) UnmarshalJSON([]byte) error { return nil }
func ( Err ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Err ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Err *Err
